export const assets = [
    {url: "./dinosaurio.png", name: "MyDino"},
    {url: "./hat.png", name: "MyHat"}, 
    {url: "./baston.png", name: "MyWalkingStick"},
    {url: "./rana-1.png", name: "FrogRun1"},
    {url: "./rana-2.png", name: "FrogRun2"},
    {url: "./rana-3.png", name: "FrogRun3"},
    {url: "./rana-4.png", name: "FrogRun4"},
    {url: "./rana-5.png", name: "FrogRun5"},
    {url: "./ui/panel-blue.png", name: "Panel"},
    {url: "./ui/blue-sign.png", name: "MyBlueSign"},
    {url: "./ui/green-sign.png", name: "MyGreenSign"},
    {url: "./ui/red-sign.png", name: "MyRedSign"},
    {url: "./ui/yellow-sign.png", name: "MyYellowSign"},
    {url: "./ui/heart.png", name: "MyHeart"},
    {url: "./ui/star.png", name: "MyStar"},
    {url: "./ui/paper-panel.png", name: "MyPaperPanel"},
    {url: "./ui/wood-panel.png", name: "MyWoodPanel"},
    {url: "./ui/wood-header.png", name: "MyWoodHeader"}
]
